### ISSUE TITLE
FindPtex.cmake does not work with version >= 2.1.0

### ISSUE THREAD

**Issue by Hippocrates** [wdas/ptexutils#4]
With the shift to storing the API version in PtexVersion.h, the section where it checks for API version in (https://github.com/wdas/ptexutils/blob/56b32c1e853fbe750e826b3b9e2e61863b5755aa/cmake/FindPTex.cmake) will fail because it only checks in Ptexture.h, and will come up with an empty string (the actual error comes when trying to perform the subsequence `REGEX MATCHALL` on an empty string). It should probably check both headers to support backwards compatibility.

**Comment by dteece** [comment]
Thanks for raising this issue. I have pushed some changes to support more recent Ptex API versions. As suggested, both headers are now checked.

**Comment by Hippocrates** [comment]
Awesome, thanks!
